/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.gui;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import ufps.mundo.SistemaHTML;

/**
 *
 * @author FERNEY JARAMILLO
 */
public class Form1 extends javax.swing.JFrame {

    private SistemaHTML mySistema;

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
        setLocationRelativeTo(this);

    }

    public SistemaHTML getMySistema() {
        return mySistema;
    }

    public void setMySistema(SistemaHTML mySistema) {
        this.mySistema = mySistema;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonURL = new javax.swing.JRadioButton();
        jRadioButtonLocal = new javax.swing.JRadioButton();
        jRadioButtonNuevo = new javax.swing.JRadioButton();
        jButtonAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        jLabel1.setText("EDITOR HTML");

        jLabel3.setText("Seleccione el lugar donde se encuentra el archivo (URL O DESKOPT) o puede crear un archivo Nuevo.");

        buttonGroup1.add(jRadioButtonURL);
        jRadioButtonURL.setText("URL ");

        buttonGroup1.add(jRadioButtonLocal);
        jRadioButtonLocal.setText("Archivo Local");
        jRadioButtonLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLocalActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNuevo);
        jRadioButtonNuevo.setText("CREAR NUEVO");
        jRadioButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNuevoActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("ACEPTAR");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ufps/fondoescritorioForm3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonURL)
                                .addGap(88, 88, 88)
                                .addComponent(jRadioButtonLocal)
                                .addGap(84, 84, 84)
                                .addComponent(jRadioButtonNuevo))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonURL)
                            .addComponent(jRadioButtonLocal)
                            .addComponent(jRadioButtonNuevo))
                        .addGap(27, 27, 27)
                        .addComponent(jButtonAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:

        if (this.jRadioButtonLocal.isSelected()) {
            JFileChooser x = new JFileChooser();
            x.showOpenDialog(this);
            int seleccion = x.showSaveDialog(x);
            String ruta="";
            if(seleccion == x.APPROVE_OPTION){
                File fichero = x.getSelectedFile();
                ruta = fichero.getAbsolutePath();
            }
            
            mySistema = new SistemaHTML(ruta);
        } else if (this.jRadioButtonURL.isSelected()) {
            FormdigitarURL k;

            k = new FormdigitarURL(this);
            k.setVisible(true);
            this.setVisible(false);
        } else if (this.jRadioButtonNuevo.isSelected()) {

            FormEditorHTML k;
            this.mySistema=new SistemaHTML();
            k = new FormEditorHTML(this);
            k.setVisible(true);



//        try{ 
//        Runtime BlockNotas=Runtime.getRuntime();
//      Process proceso=BlockNotas.exec("notepad");
//       proceso.waitFor();
//        
//        }
//       catch (IOException ioe){
//            ioe.printStackTrace();
//      }
//        catch (InterruptedException ie){
//           ie.printStackTrace();
//       }
//        }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione algun campo");



    }//GEN-LAST:event_jButtonAceptarActionPerformed
    }
    private void jRadioButtonLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLocalActionPerformed

    private void jRadioButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNuevoActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonLocal;
    private javax.swing.JRadioButton jRadioButtonNuevo;
    private javax.swing.JRadioButton jRadioButtonURL;
    // End of variables declaration//GEN-END:variables
}
